language: node_js
node_js:
- '14'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master


deploy:
  provider: heroku
  app: my-steam
  api_key:
    secure: 57900d4d-07fa-4deb-b943-424d01509e75
